FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -ldflags "-w -s" -o /agent ./internal/cmd/agent

RUN rm -rf /tmp/*

FROM scratch
COPY --from=builder /agent /agent
COPY --from=builder /tmp /tmp
COPY --from=builder /app/agent/test-data/amdgpu.ids /usr/share/libdrm/amdgpu.ids

VOLUME ["/var/lib/beszel-agent"]

ENTRYPOINT ["/agent"]
