FROM --platform=$BUILDPLATFORM oven/bun:1-alpine AS frontend

WORKDIR /app

COPY internal/site/package.json internal/site/bun.lock ./
RUN bun install --frozen-lockfile

COPY internal/site/ ./
RUN bun run build

FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
COPY --from=frontend /app/dist ./internal/site/dist

RUN apk add --no-cache unzip ca-certificates && update-ca-certificates

ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -ldflags "-w -s" -o /beszel ./internal/cmd/hub

FROM scratch
COPY --from=builder /beszel /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

VOLUME ["/beszel_data"]

EXPOSE 8090

ENTRYPOINT ["/beszel"]
CMD ["serve", "--http=0.0.0.0:8090"]
