# Docs: https://beszel.dev/guide/getting-started
# Env vars: https://beszel.dev/guide/environment-variables

networks:
  beszel-dev:

services:
  beszel:
    build:
      context: ../../../
      dockerfile: Dockerfile.hub.dev
    container_name: beszel
    restart: unless-stopped
    networks:
      - beszel-dev
    ports:
      - 8090:8090
    environment:
      APP_URL: http://localhost:8090
      ENV: dev
      VITE_HOST: beszel-frontend:5173
    command: sh -c "mkdir -p internal/site/dist && touch internal/site/dist/.gitkeep && air"
    volumes:
      - ../../../:/app
      - ./beszel_data:/app/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-frontend:
    image: oven/bun:1-alpine
    container_name: beszel-frontend
    restart: unless-stopped
    networks:
      - beszel-dev
    ports:
      - 5173:5173
    working_dir: /app
    environment:
      HUB_URL: http://beszel:8090
    command: sh -c "bun install --frozen-lockfile && bun run dev --host"
    volumes:
      - ../../../internal/site:/app

  beszel-agent:
    build:
      context: ../../../
      dockerfile: Dockerfile.agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/proc:ro
      - /sys:/sys:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8090
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}
    # healthcheck:
    #   test: ['CMD', '/agent', 'health']
    #   interval: 120s
